// Object.prototype.toString.call()

export const undefinedTag = "[object Undefined]"
export const nullTag = "[object Null]"
export const funcTag = "[object Function]"
export const genTag = "[object GeneratorFunction]"
export const asyncTag = "[object AsyncFunction]"
export const proxyTag = "[object Proxy]"
export const symbolTag = "[object Symbol]"
export const boolTag = "[object Boolean]"
export const numberTag = "[object Number]"
export const stringTag = "[object String]"
export const weakMapTag = "[object WeakMap]"
export const weakSetTag = "[object WeakSet]"
export const objectTag = "[object Object]"
export const argsTag = "[object Arguments]"
