export const ADD_TODO = "ADD_mTODO";
export const COMPLETE_ALL_TODOS = "COMPLETE_ALL_TODOS";
export const COMPLETE_TODO = "COMPLETE_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const CLEAR_COMPLETED = "CLEAR_COMPLETED";
export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";
